### ISSUE TITLE
监控文件创建路径可以设置多个吗？

### ISSUE THREAD

**Issue by lonelyice521** [thsrite/library_strm#2]
有多个网盘 这个监控文件创建路径可以设置多个吗？
试用了一下，几个问题要请教一下：
1、新转存的文件 可以自动生成strm文件， 云端删除文件和文件夹后，本地strm文件和文件夹 不会被删除。这个脚本是否还会有更新？

**Comment by thsrite** [comment]
8f15f2b2cc246631d8a66e6c0dce4650904b710d

**Comment by thsrite** [comment]
已支持
