### ISSUE TITLE
请问一下API模式怎么配置？

### ISSUE THREAD

**Issue by asd2003asd** [thsrite/library_strm#5]
sync:
  monitor_confs: [
    {
      "monitoring_mode": "compatibility",
      "source_dir": "/mnt/user/downloads/cloud/emby",
      "dest_dir": "/mnt/user/downloads/link/aliyun",
      "cloud_type": "alist",
      "cloud_path": "/mnt/user/downloads/cloud",
      "cloud_url": "192.168.0.88:5245",
      "copy_img": "True",
      "create_strm": "True"
    }
  ]   这样配置对吗？

**Comment by thsrite** [comment]
对
